const SCORE_NAME_MAP = {
	0: 'love',
	1: 'fifteen',
	2: 'thirty',
	3: 'forty'
};

const DEUCE_TEXT = 'deuce!';
const ADVANTAGE_TEXT = 'advantage';

const WINNING_SCORE = 4;
const DEUCE_SCORE_MINIMUM = 3;
const DEUCE_SCORE_DIFFERENCE = 2;

const DEFAULT_PLAYER_ONE_NAME = 'Player 1';
const DEFAULT_PLAYER_TWO_NAME = 'Player 2';

module.exports = {
	SCORE_NAME_MAP,
	DEUCE_TEXT,
	ADVANTAGE_TEXT,
	WINNING_SCORE,
	DEUCE_SCORE_DIFFERENCE,
	DEUCE_SCORE_MINIMUM,
	DEFAULT_PLAYER_ONE_NAME,
	DEFAULT_PLAYER_TWO_NAME
};
